application: home-automation-7
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /frontend
  static_dir: frontend
- url: /fonts
  static_dir: frontend/fonts
- url: /scripts
  static_dir: frontend/scripts
- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: pycrypto  
  version: "2.3"
